---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-test12
  namespace: metrics
spec:
  parallelism: 1
  script:
    configMap:
      name: 'k6-tests-unificados'
      file: 'test12_step_down.js'